export const LOAD_ARTISTS = 'LOAD_ARTISTS';
export const LOAD_ARTISTS_DONE = 'LOAD_ARTISTS_DONE';

export const SEARCH_ARTISTS = 'SEARCH_ARTISTS';
export const SEARCH_ARTISTS_SUCCESS = 'SEARCH_ARTISTS_SUCCESS';
export const SEARCH_ARTISTS_FAIL = 'SEARCH_ARTISTS_FAIL';

export const LIKE_ARTIST = 'LIKE_ARTIST';
export const LIKE_ARTIST_DONE = 'LIKE_ARTIST_DONE';
